version: '3.3'
services:
  mongodb:
    image: mongo:latest
    container_name: blog-db
    ports: 
      - 27017:27017

  api:
    image: node:20.9.0
    container_name: blog-api
    working_dir: /usr/index
    volumes:
      - ./api:/usr/index
    ports:
      - 3001:3001
    command: bash -c "npm install && npm start"
  
  blog-webapp:
    image: node:20.9.0
    container_name: blog-website
    working_dir: /usr/src/main
    volumes:
      - ./blog-webapp:/usr/src/main
    ports:
      - 5173:3000
    command: bash -c "npm install && npm run dev"